import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, ClipboardCheck, FolderKanban, Plus, Sparkles, TrendingUp, Users } from "lucide-react";
import { applications, projects } from "@/data/mock-data";
import type { Role } from "@/types";
import { Badge, Button, Card, SectionTitle } from "@/components/ui";
import { ProjectCard } from "./ProjectCard";
import { StatCard } from "./StatCard";
export function DashboardHome({ role }: { role: Role }) {
  if (role === "student") return <><SectionTitle eyebrow="Tuesday, October 9" title="Good morning, Aarav." description="Here’s what’s happening across your project journey." /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Profile strength" value="78%" detail="+12% this week" icon={TrendingUp} /><StatCard label="Applications" value="4" detail="2 awaiting review" icon={ClipboardCheck} /><StatCard label="Saved projects" value="8" detail="3 new matches" icon={FolderKanban} /></div><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_320px]"><div><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Recommended for you</h2><Link href="/student/projects" className="text-sm font-semibold text-brand">See all</Link></div><div className="grid gap-4 md:grid-cols-2">{projects.slice(0, 2).map((project) => <ProjectCard key={project.id} project={project} />)}</div></div><Card className="h-fit p-5"><div className="flex items-center gap-2"><Sparkles className="text-brand" size={18} /><h2 className="font-bold">Your next step</h2></div><p className="mt-3 text-sm leading-6 text-muted">Complete your portfolio story to get matched with more creative projects.</p><Link href="/student/assessments"><Button className="mt-5 w-full">Continue assessment <ArrowRight size={15} /></Button></Link></Card></div></>;
  if (role === "business") return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><SectionTitle eyebrow="Business workspace" title="Welcome back, Green Leaf." description="Keep your projects moving and find the right people for the work." /><Link href="/business/post-problem"><Button><Plus size={16} /> Post a problem</Button></Link></div><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Active projects" value="3" detail="1 needs your review" icon={BriefcaseBusiness} /><StatCard label="Applications" value="27" detail="+8 this week" icon={Users} /><StatCard label="Projects completed" value="6" detail="4.8 average rating" icon={CheckCircle2} /></div><div className="mt-10"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Your projects</h2><Link href="/business/projects" className="text-sm font-semibold text-brand">Manage all</Link></div><div className="grid gap-4 md:grid-cols-2">{projects.slice(0, 2).map((project) => <ProjectCard key={project.id} project={project} />)}</div></div></>;
  return <><SectionTitle eyebrow="Admin console" title="Platform overview." description="A quick pulse on users, projects and marketplace activity." /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Total users" value="1,248" detail="+14% this month" icon={Users} /><StatCard label="Live projects" value="86" detail="12 pending review" icon={FolderKanban} /><StatCard label="Successful matches" value="312" detail="92% completion rate" icon={CheckCircle2} /></div><Card className="mt-8 overflow-hidden"><div className="border-b border-line p-5"><h2 className="font-bold">Recent activity</h2></div>{applications.map((application) => <div key={application.id} className="flex items-center justify-between border-b border-line p-5 last:border-0"><div><p className="text-sm font-semibold">{application.studentName} applied to {application.projectTitle}</p><p className="mt-1 text-xs text-muted">{application.appliedAt}</p></div><Badge tone="green">{application.status}</Badge></div>)}</Card></>;
}
