import nextEnv from '@next/env';
import { neon } from '@neondatabase/serverless';
nextEnv.loadEnvConfig(process.cwd());
if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is missing');
const sql = neon(process.env.DATABASE_URL);
try {
  await sql.transaction([
    sql`INSERT INTO skillbridge.profiles(auth_user_id, username, email, full_name, role, onboarding_completed)
      VALUES ('demo:business', 'demo_business', 'business@example.invalid', 'Demo Business', 'business', true),
      ('demo:student', 'demo_student', 'student@example.invalid', 'Demo Student', 'student', true)
      ON CONFLICT(auth_user_id) DO NOTHING`,
    sql`INSERT INTO skillbridge.business_profiles(profile_id, business_name, business_type, location)
      SELECT id, 'Demo Local Café', 'Food and beverage', 'Pune' FROM skillbridge.profiles WHERE auth_user_id = 'demo:business'
      ON CONFLICT(profile_id) DO NOTHING`,
    sql`INSERT INTO skillbridge.student_profiles(profile_id, bio, skills, interests, availability, visibility)
      SELECT id, 'I build simple websites for local businesses.', ARRAY['Web development', 'Design'], ARRAY['Local businesses'], '10 hours/week', 'public'
      FROM skillbridge.profiles WHERE auth_user_id = 'demo:student' ON CONFLICT(profile_id) DO NOTHING`,
    sql`INSERT INTO skillbridge.projects(id, owner_profile_id, title, summary, problem_statement, category, location_text, required_skills, deliverables, timeline, budget_label, owner_confirmed, confirmed_version, status)
      SELECT '00000000-0000-4000-8000-000000000001'::uuid, id, 'Build a café website',
      'Help customers find our menu and opening hours.', 'Create a responsive website with a menu, location and opening hours.',
      'Web development', 'Pune / Remote', ARRAY['Web development', 'Design'], ARRAY['Responsive website', 'Menu page'],
      '3 weeks', 'Demo project', true, 1, 'published' FROM skillbridge.profiles WHERE auth_user_id = 'demo:business'
      ON CONFLICT(id) DO NOTHING`,
    sql`INSERT INTO skillbridge.applications(project_id, student_id, cover_note)
      SELECT '00000000-0000-4000-8000-000000000001'::uuid, id, 'I would love to help build your café website.'
      FROM skillbridge.student_profiles WHERE profile_id = (SELECT id FROM skillbridge.profiles WHERE auth_user_id = 'demo:student') ON CONFLICT(project_id, student_id) DO NOTHING`,
    sql`INSERT INTO skillbridge.knowledge_chunks(source_key, chunk_index, content, metadata, approved)
      VALUES ('demo:project-scoping', 0, 'A good project brief identifies the problem, measurable deliverables, required skills and a realistic timeline.',
      '{"source":"SkillBridge demo guidance","demo":true}'::jsonb, true) ON CONFLICT(source_key, chunk_index) DO NOTHING`,
  ]);
  console.log('Demo seed applied. Synthetic profiles are not login accounts. Embeddings remain unset until generated by the chosen model.');
} catch (error) { console.error('Seed failed:', error.code || error.name); process.exitCode = 1; }
