-- ==============================================================================
-- Workstream 3: Guided Questions & Owner Verification Schema
-- Original teammate proposal, retained for reference. Do not execute directly.
-- Central adaptation: migrations/003_guided_verification.sql (after 001 and 002).
-- Hand this over to the teammate owning Workstream 6 for inclusion in migrations.
-- ==============================================================================

-- 1. Modify the existing `projects` table to handle confirmation state
ALTER TABLE projects
  ADD COLUMN owner_confirmed BOOLEAN DEFAULT false,
  ADD COLUMN confirmed_at TIMESTAMP WITH TIME ZONE;

-- 2. Create the `project_questions` table
-- This stores the questions generated by the AI to clarify the brief.
CREATE TABLE project_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    question_type VARCHAR(50) NOT NULL, -- e.g., 'yes_no', 'short_text', 'multiple_choice'
    options JSONB,                      -- Used if type is 'multiple_choice'
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create the `project_answers` table
-- This stores the responses from the business owner.
CREATE TABLE project_answers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id UUID NOT NULL REFERENCES project_questions(id) ON DELETE CASCADE,
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    business_user_id UUID NOT NULL,     -- The owner who answered it
    answer_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- Ensure an owner can only answer a question once (they can update the existing row)
    CONSTRAINT unique_project_question_answer UNIQUE (question_id, project_id)
);

-- 4. Helpful Indexes
CREATE INDEX idx_project_questions_project_id ON project_questions(project_id);
CREATE INDEX idx_project_answers_project_id ON project_answers(project_id);
